name: matka
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version amnd the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  shared_preferences:
  package_info:
  device_info:
  esys_flutter_share:
  cached_network_image:
  #firebase_messaging:
  #  firebase_messaging:
  #    git:
  #      url: https://github.com/MaikuB/flutterfire.git
  #      path: packages/firebase_messaging
  #flutter_local_notifications:
  #firebase_analytics:
  #firebase_crashlytics:
  #  carousel_slider:
  #  http: ^0.12.0+2
  pin_code_text_field:
  webview_flutter:
  flutter_html:
  file_picker:
  intl:
  flutter_downloader:
  path_provider:
  #  permission_handler: ^4.2.0+hotfix.3
  progress_dialog:
  open_file:
  image_picker:
  store_redirect:
  readmore:
  dio:
  upi_india:
  expandable:
  flutter_zoom_drawer:
  polygon_clipper:
  flutter_statusbarcolor:
  url_launcher:
  fluttertoast:
  provider:
  modal_bottom_sheet:
  rate_my_app:
  pull_to_refresh:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/doublepana.png
    - assets/fullsangam.png
    - assets/halfsangam.png
    - assets/singledigit.png
    - assets/halfsangam2.jpeg
    - assets/jodidigit.png
    - assets/singlepana.png
    - assets/whatsapp.png
    - assets/triplepana.png
    - assets/googlepay.png
    - assets/paytm.png
    - assets/phonepay.png
    - assets/dataModal/menu.json
    - assets/logo.jpeg
    - assets/appbaricon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
